#pragma once

#include <string>
#include <vector>
#include <chrono>
#include <memory>
#include "imgui.h"

namespace NeuroShell {

// Command execution status
enum class CommandStatus {
    Success,
    Running,
    Failed,
    Cancelled
};

// Command block structure (like Warp's command blocks)
struct CommandBlock {
    std::string input;              // User's input command
    std::string output;             // Command output
    std::string workingDirectory;   // CWD when executed
    CommandStatus status;           // Execution status
    int exitCode;                   // Exit code
    std::chrono::system_clock::time_point timestamp;
    bool isAIGenerated;            // Was this generated by AI?
    std::string aiPrompt;          // Original NLP prompt if AI-generated
    
    CommandBlock() 
        : status(CommandStatus::Running)
        , exitCode(0)
        , isAIGenerated(false)
        , timestamp(std::chrono::system_clock::now())
    {}
};

// AI provider options
enum class AIProvider {
    OpenAI,
    Groq,
    Gemini,
    Ollama,
    None
};

// AI configuration
struct AIConfig {
    AIProvider provider;
    std::string apiKey;
    std::string model;              // e.g., "gpt-4", "gemini-pro"
    std::string endpoint;           // API endpoint URL
    float temperature;
    int maxTokens;
    
    AIConfig()
        : provider(AIProvider::None)
        , temperature(0.7f)
        , maxTokens(500)
    {}
};

// Theme colors (Tokyo Night / Warp-inspired)
struct ThemeColors {
    ImVec4 background;
    ImVec4 titleBar;
    ImVec4 commandInput;
    ImVec4 commandOutput;
    ImVec4 errorOutput;
    ImVec4 successOutput;
    ImVec4 aiPanel;
    ImVec4 text;
    ImVec4 textDim;
    ImVec4 accent;
    ImVec4 border;
    ImVec4 scrollbar;
};

// Application state
struct AppState {
    bool showAIPanel;
    bool showDemoWindow;
    bool verboseMode;
    std::string currentWorkingDir;
    AIConfig aiConfig;
    ThemeColors theme;
    
    AppState() 
        : showAIPanel(true)
        , showDemoWindow(false)
        , verboseMode(false)
    {}
};

} // namespace NeuroShell
